// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnicalSupport.Data;

namespace TechnicalSupport.Migrations
{
    [DbContext(typeof(ChatContext))]
    [Migration("20210303200430_two")]
    partial class two
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TechnicalSupport.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Chat")
                        .HasColumnType("int");

                    b.Property<int?>("ChatId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ApplicationId");

                    b.HasIndex("ChatId");

                    b.HasIndex("Status");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("Guidemployee")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUIDEmployee");

                    b.Property<Guid?>("Guiduser")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUIDUser");

                    b.HasKey("ChatId");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.Property<string>("SecondName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Sex")
                        .HasColumnType("int");

                    b.Property<string>("UserIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClientId");

                    b.HasIndex("Sex");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TechnicalSupport.Models.CommunicationType", b =>
                {
                    b.Property<int>("CommunicationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommunicationType1")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("CommunicationType");

                    b.HasKey("CommunicationTypeId");

                    b.ToTable("CommunicationType");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Detail", b =>
                {
                    b.Property<int>("DetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Chat")
                        .HasColumnType("int");

                    b.Property<int?>("CommunicationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Data")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("Guidinteracting")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUIDInteracting");

                    b.Property<int?>("RequestType")
                        .HasColumnType("int");

                    b.HasKey("DetailsId")
                        .HasName("PK__Details__BAC8628C5494B5B4");

                    b.HasIndex("Chat");

                    b.HasIndex("CommunicationType");

                    b.HasIndex("RequestType");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Dialog", b =>
                {
                    b.Property<Guid>("DialogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EmployeeId1")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("DialogId");

                    b.HasIndex("EmployeeId1");

                    b.HasIndex("UserId1");

                    b.ToTable("Dialogs");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("EmployeeGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeGUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.Property<string>("SecondName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<bool>("StatusOnline")
                        .HasColumnType("bit");

                    b.Property<int>("WorkTime")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Sex");

                    b.HasIndex("WorkTime");

                    b.HasIndex(new[] { "EmployeeGuid" }, "IX_EmployeeGUID")
                        .IsUnique();

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("TechnicalSupport.Models.EmployeeTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Guidemployy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUIDEmployy");

                    b.Property<int>("TaskCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.HasIndex("Guidemployy");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("TechnicalSupport.Models.RequestType", b =>
                {
                    b.Property<int>("RequestTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RequestType1")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("RequestType");

                    b.HasKey("RequestTypeId");

                    b.ToTable("RequestType");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Sex", b =>
                {
                    b.Property<int>("SexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SexName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Sex");

                    b.HasKey("SexId");

                    b.ToTable("Sex");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("DialogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("DialogId")
                        .IsUnique();

                    b.ToTable("Status");
                });

            modelBuilder.Entity("TechnicalSupport.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("LocalHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TechnicalSupport.Models.WorkTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("From")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("To")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("WorkTime");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Application", b =>
                {
                    b.HasOne("TechnicalSupport.Models.Chat", null)
                        .WithMany("Applications")
                        .HasForeignKey("ChatId");

                    b.HasOne("TechnicalSupport.Models.Status", "StatusNavigation")
                        .WithMany("Applications")
                        .HasForeignKey("Status")
                        .HasConstraintName("FK_Status")
                        .IsRequired();

                    b.Navigation("StatusNavigation");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Client", b =>
                {
                    b.HasOne("TechnicalSupport.Models.Sex", "SexNavigation")
                        .WithMany("Users")
                        .HasForeignKey("Sex")
                        .HasConstraintName("FK_UserSex");

                    b.Navigation("SexNavigation");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Detail", b =>
                {
                    b.HasOne("TechnicalSupport.Models.Chat", "ChatNavigation")
                        .WithMany("Details")
                        .HasForeignKey("Chat")
                        .HasConstraintName("FK_DetailsChat");

                    b.HasOne("TechnicalSupport.Models.CommunicationType", "CommunicationTypeNavigation")
                        .WithMany("Details")
                        .HasForeignKey("CommunicationType")
                        .HasConstraintName("FK_DetailsCommunicationType");

                    b.HasOne("TechnicalSupport.Models.RequestType", "RequestTypeNavigation")
                        .WithMany("Details")
                        .HasForeignKey("RequestType")
                        .HasConstraintName("FK_RequestType");

                    b.Navigation("ChatNavigation");

                    b.Navigation("CommunicationTypeNavigation");

                    b.Navigation("RequestTypeNavigation");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Dialog", b =>
                {
                    b.HasOne("TechnicalSupport.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId1");

                    b.HasOne("TechnicalSupport.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("Employee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Employee", b =>
                {
                    b.HasOne("TechnicalSupport.Models.Sex", "SexNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("Sex")
                        .HasConstraintName("FK_EmployeeSex")
                        .IsRequired();

                    b.HasOne("TechnicalSupport.Models.WorkTime", "WorkTimeNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("WorkTime")
                        .HasConstraintName("FK_WorkTime")
                        .IsRequired();

                    b.Navigation("SexNavigation");

                    b.Navigation("WorkTimeNavigation");
                });

            modelBuilder.Entity("TechnicalSupport.Models.EmployeeTask", b =>
                {
                    b.HasOne("TechnicalSupport.Models.Employee", "GuidemployyNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("Guidemployy")
                        .HasConstraintName("FK_Task_GUIDEmployy")
                        .HasPrincipalKey("EmployeeGuid")
                        .IsRequired();

                    b.Navigation("GuidemployyNavigation");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Status", b =>
                {
                    b.HasOne("TechnicalSupport.Models.Dialog", "Dialog")
                        .WithOne("Status")
                        .HasForeignKey("TechnicalSupport.Models.Status", "DialogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dialog");
                });

            modelBuilder.Entity("TechnicalSupport.Models.User", b =>
                {
                    b.HasOne("TechnicalSupport.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Chat", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Details");
                });

            modelBuilder.Entity("TechnicalSupport.Models.CommunicationType", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Dialog", b =>
                {
                    b.Navigation("Status");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Employee", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TechnicalSupport.Models.RequestType", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Sex", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Status", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("TechnicalSupport.Models.WorkTime", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
