// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnicalSupport.Data;

namespace TechnicalSupport.Migrations
{
    [DbContext(typeof(ChatContext))]
    partial class ChatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TechnicalSupport.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Chat")
                        .HasColumnType("int");

                    b.Property<int?>("ChatId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StatusNavigationId")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationId");

                    b.HasIndex("ChatId");

                    b.HasIndex("StatusNavigationId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("Guidemployee")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Guiduser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChatId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TechnicalSupport.Models.CommunicationType", b =>
                {
                    b.Property<int>("CommunicationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommunicationType1")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommunicationTypeId");

                    b.ToTable("CommunicationTypes");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Detail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Chat")
                        .HasColumnType("int");

                    b.Property<int?>("ChatNavigationChatId")
                        .HasColumnType("int");

                    b.Property<int?>("CommunicationType")
                        .HasColumnType("int");

                    b.Property<int?>("CommunicationTypeNavigationCommunicationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guidinteracting")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RequestType")
                        .HasColumnType("int");

                    b.Property<int?>("RequestTypeNavigationRequestTypeId")
                        .HasColumnType("int");

                    b.HasKey("DetailId");

                    b.HasIndex("ChatNavigationChatId");

                    b.HasIndex("CommunicationTypeNavigationCommunicationTypeId");

                    b.HasIndex("RequestTypeNavigationRequestTypeId");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Dialog", b =>
                {
                    b.Property<Guid>("DialogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EmployeeId1")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("DialogId");

                    b.HasIndex("EmployeeId1");

                    b.HasIndex("UserId1");

                    b.ToTable("Dialogs");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusOnline")
                        .HasColumnType("bit");

                    b.Property<int>("WorkTime")
                        .HasColumnType("int");

                    b.Property<int?>("WorkTimeNavigationId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("WorkTimeNavigationId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TechnicalSupport.Models.EmployeeTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Guidemployy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("GuidemployyNavigationEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TaskCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuidemployyNavigationEmployeeId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TechnicalSupport.Models.RequestType", b =>
                {
                    b.Property<int>("RequestTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RequestType1")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestTypeId");

                    b.ToTable("RequestTypes");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("DialogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status1")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DialogId")
                        .IsUnique();

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("TechnicalSupport.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("LocalHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TechnicalSupport.Models.WorkTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("From")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("To")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("WorkTimes");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Application", b =>
                {
                    b.HasOne("TechnicalSupport.Models.Chat", null)
                        .WithMany("Applications")
                        .HasForeignKey("ChatId");

                    b.HasOne("TechnicalSupport.Models.Status", "StatusNavigation")
                        .WithMany("Applications")
                        .HasForeignKey("StatusNavigationId");

                    b.Navigation("StatusNavigation");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Detail", b =>
                {
                    b.HasOne("TechnicalSupport.Models.Chat", "ChatNavigation")
                        .WithMany("Details")
                        .HasForeignKey("ChatNavigationChatId");

                    b.HasOne("TechnicalSupport.Models.CommunicationType", "CommunicationTypeNavigation")
                        .WithMany("Details")
                        .HasForeignKey("CommunicationTypeNavigationCommunicationTypeId");

                    b.HasOne("TechnicalSupport.Models.RequestType", "RequestTypeNavigation")
                        .WithMany("Details")
                        .HasForeignKey("RequestTypeNavigationRequestTypeId");

                    b.Navigation("ChatNavigation");

                    b.Navigation("CommunicationTypeNavigation");

                    b.Navigation("RequestTypeNavigation");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Dialog", b =>
                {
                    b.HasOne("TechnicalSupport.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId1");

                    b.HasOne("TechnicalSupport.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("Employee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Employee", b =>
                {
                    b.HasOne("TechnicalSupport.Models.WorkTime", "WorkTimeNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("WorkTimeNavigationId");

                    b.Navigation("WorkTimeNavigation");
                });

            modelBuilder.Entity("TechnicalSupport.Models.EmployeeTask", b =>
                {
                    b.HasOne("TechnicalSupport.Models.Employee", "GuidemployyNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("GuidemployyNavigationEmployeeId");

                    b.Navigation("GuidemployyNavigation");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Status", b =>
                {
                    b.HasOne("TechnicalSupport.Models.Dialog", "Dialog")
                        .WithOne("Status")
                        .HasForeignKey("TechnicalSupport.Models.Status", "DialogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dialog");
                });

            modelBuilder.Entity("TechnicalSupport.Models.User", b =>
                {
                    b.HasOne("TechnicalSupport.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Chat", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Details");
                });

            modelBuilder.Entity("TechnicalSupport.Models.CommunicationType", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Dialog", b =>
                {
                    b.Navigation("Status");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Employee", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TechnicalSupport.Models.RequestType", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TechnicalSupport.Models.Status", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("TechnicalSupport.Models.WorkTime", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
